name = "JuliaInterpreter"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
version = "0.12.0"
authors = ["Tim Holy <tim.holy@gmail.com>", "Kristoffer Carlsson <kcarlsson89@gmail.com>", "Shuhei Kadowaki <aviatesk@gmail.com>", "and contributors"]

[workspace]
projects = ["docs", "test"]

[deps]
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CodeTracking = "2, 3"
julia = "1.10"
